# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 383)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BarraDeProgresso = QtWidgets.QProgressBar(self.centralwidget)
        self.BarraDeProgresso.setGeometry(QtCore.QRect(520, 310, 118, 23))
        self.BarraDeProgresso.setProperty("value", 0)
        self.BarraDeProgresso.setObjectName("BarraDeProgresso")
        self.musicaSlider = QtWidgets.QSlider(self.centralwidget)
        self.musicaSlider.setGeometry(QtCore.QRect(420, 10, 201, 22))
        self.musicaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.musicaSlider.setObjectName("musicaSlider")
        self.botaoTocar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoTocar.setGeometry(QtCore.QRect(420, 40, 75, 23))
        self.botaoTocar.setObjectName("botaoTocar")
        self.botaoParar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoParar.setGeometry(QtCore.QRect(550, 40, 75, 23))
        self.botaoParar.setObjectName("botaoParar")
        self.botaoEscolher = QtWidgets.QPushButton(self.centralwidget)
        self.botaoEscolher.setGeometry(QtCore.QRect(420, 70, 61, 23))
        self.botaoEscolher.setObjectName("botaoEscolher")
        self.botaoBaixar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoBaixar.setGeometry(QtCore.QRect(560, 70, 61, 23))
        self.botaoBaixar.setObjectName("botaoBaixar")
        self.progressoLabel = QtWidgets.QLabel(self.centralwidget)
        self.progressoLabel.setGeometry(QtCore.QRect(410, 310, 101, 20))
        self.progressoLabel.setTextFormat(QtCore.Qt.AutoText)
        self.progressoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressoLabel.setObjectName("progressoLabel")
        self.botaoPular = QtWidgets.QPushButton(self.centralwidget)
        self.botaoPular.setGeometry(QtCore.QRect(540, 100, 81, 23))
        self.botaoPular.setObjectName("botaoPular")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 401, 341))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.botaoAnterior = QtWidgets.QPushButton(self.centralwidget)
        self.botaoAnterior.setGeometry(QtCore.QRect(420, 100, 81, 23))
        self.botaoAnterior.setObjectName("botaoAnterior")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 21))
        self.menubar.setObjectName("menubar")
        self.menuM_sicas = QtWidgets.QMenu(self.menubar)
        self.menuM_sicas.setObjectName("menuM_sicas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuM_sicas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botaoTocar.setText(_translate("MainWindow", "Tocar"))
        self.botaoParar.setText(_translate("MainWindow", "Parar"))
        self.botaoEscolher.setText(_translate("MainWindow", "Escolher"))
        self.botaoBaixar.setText(_translate("MainWindow", "Baixar"))
        self.progressoLabel.setText(_translate("MainWindow", "Progresso"))
        self.botaoPular.setText(_translate("MainWindow", "Pular"))
        self.botaoAnterior.setText(_translate("MainWindow", "Anterior"))
        self.menuM_sicas.setTitle(_translate("MainWindow", "Músicas"))
